### ISSUE TITLE
gmdate instead of date 

### ISSUE THREAD

**Issue by dgncan** [okulistik/aws-signature#1]
I think use gmdate() instead of date(). because I get error from aws.
https://github.com/okulistik/aws-signature/blob/e2d9e9961be4e7e5110752bdb8a5ecdf25e6ebf6/src/AwsSignature/SignatureV4.php#L54

**Comment by halil-ulu** [comment]
> I think use gmdate() instead of date(). because I get error from aws.
> https://github.com/okulistik/aws-signature/blob/e2d9e9961be4e7e5110752bdb8a5ecdf25e6ebf6/src/AwsSignature/SignatureV4.php#L54

@dgncan, gmdate() changed of by default date (3537c57)
